### ISSUE TITLE
ERROR: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.38

### ISSUE THREAD

**Issue by mrkz** [govm-project/govm#21]
When trying to run a vm after compiling govm I get the following error:
```
 % govm create --image cloud.img --cloud --efi --ram 2048
ERROR: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.38
panic: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.38

goroutine 1 [running]:
github.com/govm-project/govm/engines/docker.(*Docker).PullImage(0xc00033e3a0, 0x90ad7d, 0x9, 0x0, 0x2)
        /home/mark/go/src/github.com/govm-project/govm/engines/docker/docker.go:34 +0xc8
github.com/govm-project/govm/vm.(*VM).Launch(0xc000275e00)
        /home/mark/go/src/github.com/govm-project/govm/vm/vm.go:368 +0x1661
github.com/govm-project/govm/cli.create.func1(0xc0000f66e0, 0xc00010ad00, 0xc0000f66e0)
        /home/mark/go/src/github.com/govm-project/govm/cli/create.go:176 +0x8d3
github.com/codegangsta/cli.HandleAction(0x867440, 0x927090, 0xc0000f66e0, 0x0, 0xc00024b0e0)
        /home/mark/go/src/github.com/codegangsta/cli/app.go:501 +0xc8
github.com/codegangsta/cli.Command.Run(0x909711, 0x6, 0x0, 0x0, 0xc0002b7920, 0x1, 0x1, 0x90d127, 0xf, 0x0, ...)
        /home/mark/go/src/github.com/codegangsta/cli/command.go:165 +0x459
github.com/codegangsta/cli.(*App).Run(0xc0000f21c0, 0xc0000b4000, 0x8, 0x8, 0x0, 0x0)
        /home/mark/go/src/github.com/codegangsta/cli/app.go:259 +0x6bb
main.main()
        /home/mark/go/src/github.com/govm-project/govm/main.go:13 +0x4f

```

After removing the `go.mod` file and re-compiling, `govm` is able to launch the containerVM

**Comment by obedmr** [comment]
Thanks @mrkz for the bug report, in the meantime, a quick dirty-hack can be:

```
 export DOCKER_API_VERSION='1.38'
```
