### ISSUE TITLE
panic: repository name must be canonical

### ISSUE THREAD

**Issue by mrkz** [govm-project/govm#22]
After manually pulling the `govm/govm` docker image, trying to create a ContainerVM gets me the following error:
```
 % govm create --image cloud.img --cloud --efi --ram 2048
panic: repository name must be canonical

goroutine 1 [running]:
github.com/govm-project/govm/engines/docker.(*Docker).PullImage(0xc0002f16e0, 0x8c0ee5, 0x11, 0x0, 0x935060)
        /home/mark/go/src/github.com/govm-project/govm/engines/docker/docker.go:34 +0xb1
github.com/govm-project/govm/vm.(*VM).setVNC(0xc000241e00, 0xc0002dca50, 0xd, 0xc0002dcbe9, 0x5, 0x1b, 0xc000398000)
        /home/mark/go/src/github.com/govm-project/govm/vm/vm.go:211 +0x93
github.com/govm-project/govm/vm.(*VM).Launch(0xc000241e00)
        /home/mark/go/src/github.com/govm-project/govm/vm/vm.go:420 +0x13a1
github.com/govm-project/govm/cli.create.func1(0xc0000c0b00, 0x1010100, 0xc0000c0b00)
        /home/mark/go/src/github.com/govm-project/govm/cli/create.go:176 +0x8d3
github.com/codegangsta/cli.HandleAction(0x822c80, 0x8d9128, 0xc0000c0b00, 0xc000212a00, 0x0)
        /home/mark/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:490 +0xc8
github.com/codegangsta/cli.Command.Run(0x8bca5b, 0x6, 0x0, 0x0, 0xc000283890, 0x1, 0x1, 0x8c001a, 0xf, 0x0, ...)
        /home/mark/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/command.go:210 +0x9a2
github.com/codegangsta/cli.(*App).Run(0xc0000a31e0, 0xc00001e080, 0x8, 0x8, 0x0, 0x0)
        /home/mark/go/pkg/mod/github.com/codegangsta/cli@v1.20.0/app.go:255 +0x687
main.main()
        /home/mark/go/src/github.com/govm-project/govm/main.go:13 +0x4f
```

**Comment by mrkz** [comment]
I could reach this state after I proceed removing the go.mod file as stated on issue #21

**Comment by obedmr** [comment]
With latest changes in `govm` this issue should be fixed for now. @mrkz, when you have a chance, could you please validate it?

**Comment by klihub** [comment]
@obedmr I still run into this problem using [113edd9](https://github.com/govm-project/govm/commit/113edd9978785312275d71ffaf881f7d38a308bd).

For the time being I use this as a workaround:
```
git clone https://github.com/govm/govm
docker build govm -f govm/Dockerfile -t govm/govm:latest
```

I'm running with these:
```
klitkey1-mobl cri-resource-manager $ cat /etc/os-release 
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
klitkey1-mobl cri-resource-manager $ uname -r
5.7.7-100.fc31.x86_64
klitkey1-mobl cri-resource-manager $ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
